### ISSUE TITLE
Failed to build from source

### ISSUE THREAD

**Issue by luked99** [git-for-windows/git-sdk-64#2]
I downloaded the sdk and tried to build, but it failed:

    $ sdk build git
    ....
    ....
    git-compat-util.h:321:10: fatal error: openssl/ssl.h: No such file or directory
     #include <openssl/ssl.h>

Windows 7.
git is at e2d2aac684

**Comment by dscho** [comment]
Hmm, this file should be there: https://github.com/git-for-windows/git-sdk-64/tree/master/mingw64/include/openssl/

**Comment by luked99** [comment]
I think the file is present, but there's some kind of weird path problem going on.

**Comment by dscho** [comment]
> I think the file is present, but there's some kind of weird path problem going on.

Probably. You were quite a bit scarce on details. How do you call into the SDK? Do you run the `git-bash.exe` from the top-level directory?

**Comment by jglathe** [comment]
Had a similar issue here (also on linux, but there you need to install libopenssl-dev and it builds). Using git-bash.exe seems to rectify it. Build went through.

**Comment by dscho** [comment]
> Using git-bash.exe seems to rectify it.

What else would you use?

**Comment by jglathe** [comment]
For whatever reason I had an MSYS2 terminal open after initial installation. Not sure if it was my readme-aversion, but I was sort of lost there... Anyway. Building with visual studio doesn't work, gives the same error... mingw.h: openssl/ssl.h not found. Curious. Same first error on all toolchains I tried.

**Comment by dscho** [comment]
@jglathe could you please kindly explain in a lot of detail how you try to build Git? Because it sure is not the way recommended in https://github.com/git-for-windows/git/wiki/Building-Git. And without gracing others with that kind of rather crucial information, it is not help you will get, but frustration, and not only you.

**Comment by dscho** [comment]
> You were quite a bit scarce on details.

@luked99 I assume you are no longer having this issue, or are no longer interested in seeing it resolved, judging by the deafening silence.

So I'll just close this unhappy and frustrating ticket.
