### ISSUE TITLE
SSH doesn't always work

### ISSUE THREAD

**Issue by tigerjack** [git-for-windows/git-sdk-64#20]
I'm having troubles using ssh with git-sdk-64. Basically, if I try to connect to a server, I get a "Permission denied" error. If, on the other hand, I use a Powershell or even WSL I get the usual password prompt. 
This problem only appears with a few servers, while doesn't appear on others (I still haven't figured out which kind of server).
Do you know what the problem could be?

**Comment by dscho** [comment]
Could you open this ticket over at https://github.com/git-for-windows/git/issues/new, filling out the bug reporting template as well as you can? Thank you.
