### ISSUE TITLE
sdk cd can't find refs/heads/master on fresh installs

### ISSUE THREAD

**Issue by rimrul** [git-for-windows/git-sdk-64#25]
When initially running `sdk cd build-extra` on a fresh install, it complains

```
error: refname refs/heads/master not found
fatal: Umbenennung des Branches fehlgeschlagen
Could not change directory to 'build-extra'
```

`Umbenennung des Branches fehlgeschlagen` means `renaming the branch failed`. The same thing happens on `sdk cd git` and `sdk cd msys2-runtime`. `cd /usr/src/git` (or `/usr/src/build-extra` or `/usr/src/MSYS2-packages`) followed by `git pull origin main` seems to fix the issue.

**Comment by rimrul** [comment]
I can't quite figure out the source of the first error.

The second error seems to come from [git-sdk.sh#L241](https://github.com/git-for-windows/build-extra/blob/main/git-extra/git-sdk.sh#L241).

The third error seems to come from [git-sdk.sh#L195](https://github.com/git-for-windows/build-extra/blob/main/git-extra/git-sdk.sh#L195).

**Comment by dscho** [comment]
@rimrul thank you for the report! A fix is rolling out: https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=58583&view=results.
