### ISSUE TITLE
build-extra installer doesn't work anymore

### ISSUE THREAD

**Issue by brice-gros** [git-for-windows/git-sdk-64#29]
build-extra installer [git-sdk-1.0.7](https://github.com/git-for-windows/build-extra/releases/tag/git-sdk-1.0.7) doesn't work anymore due to the removal of the master branch from this repo.
The fix is already present in [build_extra](https://github.com/git-for-windows/build_extra), only a corresponding release is missing

**Comment by dscho** [comment]
Acknowledged. In the meantime, please use the work-around to clone https://github.com/git-for-windows/git-sdk-64 (or for 32-bit, https://github.com/git-for-windows/git-sdk-32) manually.

**Comment by dscho** [comment]
There you go: https://github.com/git-for-windows/build-extra/releases/tag/git-sdk-1.0.8

**Comment by PhilipOakley** [comment]
Hi @dscho 

What's the 'right' way of installing this on top of an already installed previous version (If needed at all)? 

I'm also having a separate issue with the package updates for mingw32, mingw64, and msys because of the retiral of some PGP keys due to the change of maintainer which I haven't managed to get past yet But not sure where it's best to discuss that.

**Comment by dscho** [comment]
> What's the 'right' way of installing this on top of an already installed previous version (If needed at all)?

I typically `git -C /c/git-sdk-64 pull` (using Git Bash, not Git SDK Bash), but that requires no Git SDK processes to be running. And it only includes the packages tracked in `git-sdk-64`.

You might be better off using `pacman -Syu`.

> I'm also having a separate issue with the package updates for mingw32, mingw64, and msys because of the retiral of some PGP keys due to the change of maintainer which I haven't managed to get past yet But not sure where it's best to discuss that.

You will have to use `pacman-key --recv-key <key> && pacman-key --lsign-key <key>` to fix that.

**Comment by PhilipOakley** [comment]
Thanks @dscho,

Just clarifying a few points out of an abundance of caution... probably
with more detail than needed but...

On 31/10/2020 22:11, Johannes Schindelin wrote:
>
>     What's the 'right' way of installing this on top of an already
>     installed previous version (If needed at all)?
>
> I typically git -C /c/git-sdk-64 pull (using Git Bash, not Git SDK
> Bash), but that requires no Git SDK processes to be running. And it
> only includes the packages tracked in git-sdk-64.
>
The fetch part downloaded ok, but the merge/checkout failed. It looks
like I've been on a detached head for a long long time,  and also that I
left myself on a stashed  head back at the end of May (on e27af3962e8
2020-05-18 04:08:44)  while attempting an earlier update of the sdk (the
start of PGP sign fail).

It feels like the right approach to resolve the final  pull step may be
`git reset --hard origin/main`, but I'm concerned about consequences.

Would I be right that the sdk repo has no submodules and the 'pull'
update is meant to be equivalent to the `pacman -Syu`? (I believe it is).

i.e. git reset --hard origin/main  # anything to be cleaned?

The first commit I have locally in the SDK repo is from 2019-03-02
03:11:44 (c0c5cc617), which I think is when I got the current PC.  The
shall file lists:
8c1d0b1d769b9f0162c65cdf857d816e76760eda
c0c5cc61722eb33966fcb9f167d4c597b941d1e0

My local sdk repo's objects file is now 5.8GB, 7 packs.

My main concern would be affecting the usr/src/<sub-projects>
directories. Plus I've got a clang32 and clang64 directory immediately
at the 'root' level (e.g. C:\git-sdk-64\clang64), but I could delete and
restart that, as long it it didn't have ripples...

> You might be better off using pacman -Syu.
>

I had been using that for a long while, then hit the problem below,
which I thought I'd tried all the suggestions from the up streams
without luck. There are 3 keys currently "missing" (retired...)

>     I'm also having a separate issue with the package updates for
>     mingw32, mingw64, and msys because of the retiral of some PGP keys
>     due to the change of maintainer which I haven't managed to get
>     past yet But not sure where it's best to discuss that.
>
> You will have to use pacman-key --recv-key <key> && pacman-key
> --lsign-key <key> to fix that.
>
Currently, for me, if get (if run in CMD window)
'pacman-key' is not recognized as an internal or external command,
operable program or batch file.

or Bash [Ahh that was the Mingw64 bash]
$ pacman-key --recv-key 4A6129F4E4B84AE46ED7F635628F528CF3053E04
bash: pacman-key: command not found

A quick web search suggests that I may need to update pacman itself first...
But
phili@Philip-Win10 MINGW64 /c/git-sdk-64 ((e27af3962...))
$ pacman -Syy
bash: pacman: command not found

Hmm. getting myself lost here. So start a fresh `SDK-64:/` window

Welcome to the Git for Windows SDK!

The common tasks are automated via the `sdk` function;
See `sdk help` for details.

phili@Philip-Win10 MINGW64 / ((e27af3962...))
$ pacman
error: mingw32: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
:: Import PGP key 4A6129F4E4B84AE46ED7F635628F528CF3053E04? [Y/n] n
error: mingw64: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
:: Import PGP key 4A6129F4E4B84AE46ED7F635628F528CF3053E04? [Y/n]


That's naff! a bit catch 22. try:

phili@Philip-Win10 MINGW64 / ((e27af3962...))
$ pacman-key --recv-key  4A6129F4E4B84AE46ED7F635628F528CF3053E04
gpg: keyserver receive failed: General error
==> ERROR: Remote key not fetched correctly from keyserver.

hmph. Still a bit stuck/unsure.

Thought it worth at least posting 'what I've tried so far' just in case
anyone can clarify what to do.

--
Philip

**Comment by PhilipOakley** [comment]
On 01/11/2020 14:57, Philip Oakley wrote:
> Thanks @dscho,
>
> Just clarifying a few points out of an abundance of caution... probably
> with more detail than needed but...
>
> On 31/10/2020 22:11, Johannes Schindelin wrote:
> >
> > What's the 'right' way of installing this on top of an already
> > installed previous version (If needed at all)?
> >
> > I typically git -C /c/git-sdk-64 pull (using Git Bash, not Git SDK
> > Bash), but that requires no Git SDK processes to be running. And it
> > only includes the packages tracked in git-sdk-64.
> >
> The fetch part downloaded ok, but the merge/checkout failed. It looks
> like I've been on a detached head for a long long time,  and also that I
> left myself on a stashed  head back at the end of May (on e27af3962e8
> 2020-05-18 04:08:44)  while attempting an earlier update of the sdk (the
> start of PGP sign fail).
>
> It feels like the right approach to resolve the final  pull step may be
> `git reset --hard origin/main`, but I'm concerned about consequences.
>
> Would I be right that the sdk repo has no submodules and the 'pull'
> update is meant to be equivalent to the `pacman -Syu`? (I believe it is).
>
> i.e. git reset --hard origin/main  # anything to be cleaned?
>
> The first commit I have locally in the SDK repo is from 2019-03-02
> 03:11:44 (c0c5cc617), which I think is when I got the current PC.  The
> shall file lists:
> 8c1d0b1d769b9f0162c65cdf857d816e76760eda
> c0c5cc61722eb33966fcb9f167d4c597b941d1e0
>
> My local sdk repo's objects file is now 5.8GB, 7 packs.
>
> My main concern would be affecting the usr/src/<sub-projects>
> directories. Plus I've got a clang32 and clang64 directory immediately
> at the 'root' level (e.g. C:\git-sdk-64\clang64), but I could delete and
> restart that, as long it it didn't have ripples...
>
> > You might be better off using pacman -Syu.
> >
>
> I had been using that for a long while, then hit the problem below,
> which I thought I'd tried all the suggestions from the up streams
> without luck. There are 3 keys currently "missing" (retired...)
>
> > I'm also having a separate issue with the package updates for
> > mingw32, mingw64, and msys because of the retiral of some PGP keys
> > due to the change of maintainer which I haven't managed to get
> > past yet But not sure where it's best to discuss that.
> >
> > You will have to use pacman-key --recv-key <key> && pacman-key
> > --lsign-key <key> to fix that.
> >
> Currently, for me, if get (if run in CMD window)
> 'pacman-key' is not recognized as an internal or external command,
> operable program or batch file.
>
> or Bash [Ahh that was the Mingw64 bash]
> $ pacman-key --recv-key 4A6129F4E4B84AE46ED7F635628F528CF3053E04
> bash: pacman-key: command not found
>
> A quick web search suggests that I may need to update pacman itself
> first...
> But
> phili@Philip-Win10 MINGW64 /c/git-sdk-64 ((e27af3962...))
> $ pacman -Syy
> bash: pacman: command not found
>
> Hmm. getting myself lost here. So start a fresh `SDK-64:/` window
>
> Welcome to the Git for Windows SDK!
>
> The common tasks are automated via the `sdk` function;
> See `sdk help` for details.
>
> phili@Philip-Win10 MINGW64 / ((e27af3962...))
> $ pacman
> error: mingw32: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
> :: Import PGP key 4A6129F4E4B84AE46ED7F635628F528CF3053E04? [Y/n] n
> error: mingw64: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
> :: Import PGP key 4A6129F4E4B84AE46ED7F635628F528CF3053E04? [Y/n]
>
>
> That's naff! a bit catch 22. try:
>
> phili@Philip-Win10 MINGW64 / ((e27af3962...))
> $ pacman-key --recv-key  4A6129F4E4B84AE46ED7F635628F528CF3053E04
> gpg: keyserver receive failed: General error
> ==> ERROR: Remote key not fetched correctly from keyserver.
>
> hmph. Still a bit stuck/unsure.
>
> Thought it worth at least posting 'what I've tried so far' just in case
> anyone can clarify what to do.
>
> --
Having hit the worry merry-go-round (email above), the 'clean' man page
helped with pointing to the regular .gitignore file checks, which then
showed that the various concerned sub-directories were being ignored for
changes and cleaning.

I just realised I will need to exclude my clang32/64 sub-directories as
they aren't in the .gitignore, so the exclude `-e 'clang*'` is I think
needed for the `git clean` (I hope I get the quoting right, or maybe
just have two `-e pattern`s).

Then try the pacman update.

Philip

**Comment by dscho** [comment]
Well, it really is more of an "either/or". Either you go with `git pull`, or you do `pacman`. It does not really make sense to do both, except maybe for myself, to make sure that I catch bugs in the `git-sdk-64` early.

**Comment by PhilipOakley** [comment]
> Either you go with `git pull`, or you do `pacman`

However, currently both are failing for me, so it's a bit catch 22 with rather too many XY problem issues to get past. 


I.e.

- If I try checking out origin/main I get various .exe/.dll "Unlink of file" fails.
```
$ git reset --hard origin/main
Unlink of file 'usr/bin/dirmngr.exe' failed. Should I try again? (y/n) n
error: unable to unlink old 'usr/bin/dirmngr.exe': Invalid argument
Unlink of file 'usr/bin/msys-2.0.dll' failed. Should I try again? (y/n) n
error: unable to unlink old 'usr/bin/msys-2.0.dll': Invalid argument
Unlink of file 'usr/bin/msys-gcrypt-20.dll' failed. Should I try again? (y/n) n
error: unable to unlink old 'usr/bin/msys-gcrypt-20.dll': Invalid argument
```
(I think the "Invalid argument" is just our -1 return code).


- If I try the pacman updates I get the key failures.

- If I try the sdk I get the same key failures

```
$ sdk cd  msys2-runtime
...
==> Making package: msys2-runtime 3.1.7-4 (Sat, Oct 31, 2020  1:30:59 PM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
error: mingw32: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
:: Import PGP key 4A6129F4E4B84AE46ED7F635628F528CF3053E04? [Y/n]
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: mingw64: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
:: Import PGP key 4A6129F4E4B84AE46ED7F635628F528CF3053E04? [Y/n]
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: msys: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
...
```
So at the moment, I'm flailing around a bit trying to get to a firm state.

I was even wondering about having a Windows config variable to allow the above errors to be temporarily  converted to warnings to make progress in a slightly different direction (a checkout that appears to have those listed files as being reverted..)

**Comment by dscho** [comment]
> $ git reset --hard origin/main
> Unlink of file 'usr/bin/dirmngr.exe' failed. Should I try again? (y/n) n

That's because `dirmngr` is still running, I am certain. Once you stop it (e.g. via `gpgconf --kill dirmngr`) that'll no longer be an issue.

>     * If I try the pacman updates I get the key failures.

You might be able to fix them via `gpg --recv-key <key> && gpg --lsign-key <key>`, too.

In any case, if you haven't used your copy of the SDK for a while, it might be a good idea to just throw it away and start anew. It's not like you were in the middle of some work that mustn't be lost, right?

**Comment by PhilipOakley** [comment]
I had decided that I was in the sand trap, so I've renamed the old SDK install, and started a new one which installed Ok and `make install` and `sdk build git-and-installer` all completed successfully.

The PGP key thing does get a lot of hits for folks having had problems with time limiting issues, but the new sdk has side stepped that,

I've still to fetch any work I had from my old sdk, and ensure my Github forks all match up, (there's plenty / too much of half complete stuff to just lose..;-)

**Comment by PhilipOakley** [comment]
In case it helps anyone: While comparing my old and new installs, I did notice the [SDK-64 .gitignore](https://github.com/git-for-windows/git-sdk-64/commit/980e8eb1c319416ce8da9876b5c43a107f4321c9) change for the pacman GNU Privacy Guard folder, which had been one of the areas mentioned in the [MSYS2 News](https://www.msys2.org/news/) for fixing the missing signature.

The pacman updates appear to run fine now.
