### ISSUE TITLE
Do we need /etc/pacman.d/mirrorlist.git-for-windows?

### ISSUE THREAD

**Issue by rimrul** [git-for-windows/git-sdk-64#37]
The other mirror lists seemingly get included from `/etc/pacman.conf` but we specify our package servers directly in there and the servers in the mirrorlist file appear to be quite outdated.

**Comment by dscho** [comment]
Right, we need to override some of MSYS2's packages, and therefore the mirrorlist approach does not work.

I'm fine with removing the mirrorlist.

**Comment by dscho** [comment]
I _think_ it's maintained in `build-extra`.

**Comment by rimrul** [comment]
The commit introducing it claims it's from the git-extra post-install.

**Comment by dscho** [comment]
> 
> 
> The commit introducing it claims it's from the git-extra post-install.

You mean debcb1bacdd6ccceafb5cf224ee51e542b4a7530, right?

I fear that my commit message is probably a bit incorrect here, as I do not find _anything_ in git-for-windows/build-extra@114b5d3532ef2e119df13a48ab4325ea41b7dc07 that might explain this file.

I guess the best course of action is to simply remove that file, as I must have created it manually in the course of trying to Make Things Work, back in 2016.

**Comment by green-leafe** [comment]
skulle vørt inne på tor

**Comment by dscho** [comment]
@rimrul the issue did not exist in `git-sdk-32`, so I call this one closed.
