### ISSUE TITLE
How to remove welcome message from prompt?

### ISSUE THREAD

**Issue by shankar2k** [git-for-windows/git-sdk-64#38]
Every time I start up a bash prompt it displays the message:

> Welcome to the Git for Windows SDK!
> 
> The common tasks are automated via the `sdk` function;
> See `sdk help` for details.

Also, whenever I restart Windows, a link to "Git SDK 64-bit" keeps getting added back to the desktop.

How can I both remove this welcome message and stop this link from being added to the desktop at login?

**Comment by rimrul** [comment]
You can comment out [Line 446](https://github.com/git-for-windows/git-sdk-64/blob/183888c703b09026622d40190260275629c143f9/etc/profile.d/git-sdk.sh#L446) and [Line 449](https://github.com/git-for-windows/git-sdk-64/blob/183888c703b09026622d40190260275629c143f9/etc/profile.d/git-sdk.sh#L449) of `/etc/profile.d/git-sdk.sh`. This won't survive an update of `git-extra`, though.

**Comment by dscho** [comment]
@shankar2k are you even sure that you want to develop Git for Windows? That would be the only reason for you to use Git for Windows' SDK.

**Comment by shankar2k** [comment]
I originally installed Git Bash, and then later MSYS. I wanted to integrate Git into my MSYS configuration, so I followed the instructions [here](https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper). It after I did this that I started to see this Git for Windows SDK prompt and desktop icon
