### ISSUE TITLE
Error: RPC failed every time I try to --recursive download the .git

### ISSUE THREAD

**Issue by Argonath60** [git-for-windows/git-sdk-64#40]
I get this output
C:\Users\XXXXX\eclipse-workspace>git clone --recursive https://github.com/git-for-windows/git-sdk-64.git
Cloning into 'git-sdk-64'...
remote: Enumerating objects: 503776, done.
remote: Counting objects: 100% (1268/1268), done.
remote: Compressing objects: 100% (889/889), done.
**error: RPC failed; curl 56 OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0**
error: 668 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

Is the git-sdk-64.git built properly?

**Comment by rimrul** [comment]
What windows version are you using? 

What version of Git for Windows are you using? 

Why `--recursive`?

Did you try changing the SSL backend?

**Comment by Argonath60** [comment]
Latest version of windows and latest version of git both installed yesterday
I wondered about —recursive but thats what the author of the install states
as necessary
As a newbie to SSL I have no idea what you mean by the SSL backend.
Sorry.

**Comment by dscho** [comment]
> As a newbie to SSL I have no idea what you mean by the SSL backend.

Try `git -c http.sslbackend=schannel clone ...`

>  **error: RPC failed; curl 56 OpenSSL SSL_read: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac, errno 0**

In the past, when I encountered similar issues, the usual reason was a, let's say, "opinionated" proxy server. Or flaky network connections. Or both.

But why is this ticket on the `git-sdk-64` repository? Isn't this a _Git_ issue rather than a _Git for Windows SDK_ issue?

**Comment by Argonath60** [comment]
I thought the problem was with the file. It always failed at the end within
1500 bytes of the end of the dowload.
I will try your suggestion.
