### ISSUE TITLE
Suggestion: add `mingw-w64-python-pygments` to the SDK, so GDB syntax-highlights source code

### ISSUE THREAD

**Issue by phil-blain** [git-for-windows/git-sdk-64#46]
It would be nice if the GDB available in the SDK would color source code (i.e. with the  `list` command or the in the TUI.). The easiest way to do that is simply to have the Python Pygments library installed; GDB should find it and use it (it's way easier than building GDB with the GNU source-highlight library, which - for me - seems to never results in a working build).

1. Is this the right repo to open such an issue  (build-extra does not have the "Issues" tab) ?
2. I'm not sure of what the process of adding a package to the SDK would look like. I looked through the wiki but could not find the info (maybe I did not look hard enough!)

**Comment by dscho** [comment]
Why not just manually install it yourself? `pacman -Syy mingw-w64-x86_64-python-pygments` is your friend.

As to installing it by default: the SDK is already way too large as it is, therefore I do not want to add more packages, especially when they are not essential to build Git for Windows.

**Comment by phil-blain** [comment]
I thought you were all about making things nicer for the user out of the box ;) 

Joke aside, I’ll add a note to the Debugging Git page of the wiki instead :)

**Comment by dscho** [comment]
> I thought you were all about making things nicer for the user out of the box ;)

Heh. Within reason, Phil, within reason.

> Joke aside, I’ll add a note to the Debugging Git page of the wiki instead :)

Thank you!

**Comment by phil-blain** [comment]
Added here: https://github.com/git-for-windows/git/wiki/Debugging-Git#source-code-highlighting-in-gdb
