### ISSUE TITLE
Path with spaces not working in SDK installer

### ISSUE THREAD

**Issue by aakriti-jain** [git-for-windows/git-sdk-64#6]
I tried to install the SDK in path `E:\projects\git sdk` which produced the following error later:

![screenshot 3](https://user-images.githubusercontent.com/36819503/49600738-e6193100-f9a9-11e8-8973-2ba426c0abe0.png)

I believe the spaces has not been escaped in the installer script.

**Comment by PhilipOakley** [comment]
It is an unfortunate problem at the moment. The best way around it is to use a dash between `git` and `sdk`, i.e. create a director `git-sdk`.  
It is partly because some GNU tools would appear to be intolerant of spaces in paths.

**Comment by aakriti-jain** [comment]
Yes @PhilipOakley  I did the same. But had to re-download and re-install the whole package.
For the solution, I guess the issue can be tackled if the spaces are properly escaped or the path is enclosed in quotes.

**Comment by PhilipOakley** [comment]
The need to re-download and re-install would be a pain. 

Maybe the installer should detect the space in path issue and warn early, so that it can be fixed by the user without delay. Another 'up for grabs' issue ;-)

Fixing the GNU tools etc is probably a longer harder road..

**Comment by dscho** [comment]
I am very sorry that you had to download 550MB twice :-(

It won't help you, but I think I fixed this in the PR git-for-windows/build-extra#220
