### ISSUE TITLE
Onboarded ``msgcat`` binary is broken

### ISSUE THREAD

**Issue by egeakman** [git-for-windows/git-sdk-64#65]
``msgcat -o file.po file.po`` command produces syntax errors in .po files.

Turns

```gettext-catalog
#: library/stdtypes.rst:419 library/stdtypes.rst:1171
#: library/stdtypes.rst:2397 library/stdtypes.rst:3615
msgid "\\(4)"
msgstr "\\(4)"
```

to

```gettext-catalog
#: library/stdtypes.rst:419 library/stdtypes.rst:1171
#: library/stdtypes.rst:2397
 library/stdtypes.rst:3615
msgid "\\(4)"
msgstr "\\(4)"
```

which is syntactically wrong. However, on some files, it does keep it the correct way. The above example is from [python/python-docs-tr (library/stdtypes.po)](https://github.com/python/python-docs-tr/blob/3.11/library/stdtypes.po).

It also adds whitespace at the top of the first msgid-msgstr pair.

```diff
# Python Documentation Turkish Translation
# Copyright (C) 2001-2023, Python Software Foundation
# This file is distributed under the same license as the Python package.
-#
+# 
msgid ""
msgstr ""
```

Using [other binaries](https://github.com/vslavik/gettext-tools-windows), however, doesn't produce any of these errors.

**Comment by dscho** [comment]
Is this an issue also with regular [MSYS2](https://www.msys2.org/)?

**Comment by egeakman** [comment]
> Is this an issue also with regular [MSYS2](https://www.msys2.org/)?

Tried just now and yes.

**Comment by dscho** [comment]
> Should I move this issue to https://github.com/msys2/MSYS2-packages?

Yes, I would strongly advise to do that.

**Comment by egeakman** [comment]
Sorry, I didn't know the other repo at the time.
