### ISSUE TITLE
make WINSSL default

### ISSUE THREAD

**Issue by tsraza** [git-for-windows/git-sdk-64#7]
Make the windows secure channel option the default in the installer for finding SSL certificates

**Comment by PhilipOakley** [comment]
Hi @tsraza, 

Maybe a PR to make it easier to implement; Plus a solid commit message rationale on the pros and cons of the different approaches (I'm ignorant on the matter).

**Comment by tsraza** [comment]
moving to https://github.com/git-for-windows/git/issues/2168
