### ISSUE TITLE
Removal of e-Tugra root certificate 

### ISSUE THREAD

**Issue by nagaripratap** [git-for-windows/git-sdk-64#74]
Description
Certifi 2023.07.22 removes root certificates from "e-Tugra" from the root store. These are in the process of being removed from Mozilla's trust store.

e-Tugra's root certificates are being removed pursuant to an investigation prompted by reporting of security issues in their systems. Conclusions of Mozilla's investigation can be found [here](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A).

Informations

Manifest Path : [mingw32/etc/ssl/certs/ca-bundle.trust.crt](https://github.com/git-for-windows/git-sdk-64/blob/894191270a78a83b804aeb24d8328320419445a5/mingw32/etc/ssl/certs/ca-bundle.trust.crt#L1941)

**Comment by dscho** [comment]
This here repository actually consumes the MSYS2 packages. Would you mind working on the `mingw-w64-ca-certificates` package in https://github.com/msys2/MINGW-packages instead? Git for Windows will then reap the benefits from that.

**Comment by rimrul** [comment]
> No Ca root certificates on mentioned repository, traces found only on [git-sdk-64](https://github.com/git-for-windows/git-sdk-64)

No certificates, but [the packaging info](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-ca-certificates) that [`mingw32/etc/ssl/certs/ca-bundle.trust.crt`](https://github.com/git-for-windows/git-sdk-64/blob/894191270a78a83b804aeb24d8328320419445a5/mingw32/etc/ssl/certs/ca-bundle.trust.crt#L1941) and [`mingw64/etc/ssl/certs/ca-bundle.trust.crt`](https://github.com/git-for-windows/git-sdk-64/blob/894191270a78a83b804aeb24d8328320419445a5/mingw64/etc/ssl/certs/ca-bundle.trust.crt#L1941) gets built from. And don't forget about [`ca-certificates`](https://github.com/msys2/MSYS2-packages/tree/master/ca-certificates) for [`/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt`](https://github.com/git-for-windows/git-sdk-64/blob/894191270a78a83b804aeb24d8328320419445a5/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt#L1882).

**Comment by dscho** [comment]
I don't see any updates at http://ftp.debian.org/debian/pool/main/c/ca-certificates/, from which MSYS draws their certificates. Those packages seem to draw from the Git repository at https://salsa.debian.org/debian/ca-certificates, which also did not see any update yet.

I don't really feel comfortable trying to move faster than the upstream projects. As far as I understand, there has not been any breach, just a loss of trust on Mozilla's part.

**Comment by lazka** [comment]
I've also noticed that Debian is quite slow with updating their list in general some time ago and opened https://github.com/msys2/MSYS2-packages/issues/3509 for syncing from Mozilla directly like fedora does.
